### ISSUE TITLE
Missing from MM: Internal compute capacity?

### ISSUE THREAD

**Issue by malloryfreeberg** [inab/fega-mm#51]
We have the following in the [FEGA Node Operations Guidelines](https://ega-archive.org/files/EGA-Node-Operations-v1.pdf):

> Compute
> - Purpose
>   - Computing power to ensure that day to day EGA operations can be supported in a timely fashion;
> - Features
>   - Support ETL pipeline, encryption/decryption, quality assessments, calculations on what is being archived, and a development/testing environment;
> - Central EGA adopted solution
>   - HPC compute farm and network storage in an isolated part of institutional network only accessible to authorised personnel. Compute resources required depends on submission throughput.
> 

It seems we are missing this from the FEGA MM? I see domains / subdomains for network, security, and storage, but not for computing capacity. This category is important for things like encryption processes, quality assessment, and any other parts of a node's ETL pipeline.

**Comment by lauportell** [comment]
- Need to add compute capacity for interal porpuses (encryption, quality assessment) in the MM but differenciate it from compute capacity for analysis, which shouldn't be in the model.
- Make it a useful indicator (since it is easy to reach) (TBD)
- Add an intro paragraph to make clear that compute capacity is not for analysis
- Make a draft of how the different levels will look like for the next meeting
